* Business Intelligence with R

This small project is the study exercises for the book "Business
Intelligence with R" by Dwight Barry is a data scientist at Seattle
Children’s Hospital, in Seattle, Washington, USA.

* Introduction

The growth of R has been phenomenal over the past several years,
reaching out past academia and research labs into the daily activities
of business and industry. More and more line-level analysts are
supplementing their SQL or Excel skills with R, and more and more
businesses are hiring analysts with R skills to bridge the increasing
gap between business needs and on-hand analytical resources.

While there are many books that explore the use of R in statistics and
data science, nearly all of them are set as a series of case studies
or are written predominantly for academic audiences as
textbooks. There are also many R cookbooks, but they tend to cover the
breadth of R’s capabilities and options. This book aims to provide a
cookbook of R recipes that are specifically of use in the daily
workflow of data scientists and analysts in business and industry.

Business Intelligence with R is a practical, hands-on overview of many
of the major BI/analytic tasks that can be accomplished with R. It is
not meant to be exhaustive—there is always more than one way to
accomplish a given task in R, so this book aims to provide the
simplest and/or most robust approaches to meet daily workflow
needs. It can serve as the go-to desk reference for the professional
analyst who needs to get things done in R. From setting up a project
under version control to creating an interactive dashboard of a data
product, this book will provide you with the pieces to put it all
together.

Original code found [[https://github.com/Rmadillo/business_intelligence_with_r][here]].

[Tue Aug 16 15:23:52 CDT 2016]

Twitter: @smendozab

EOF
